Always configure creds prior to log upload for multi-arch CI (#4242)
## Motivation

Related to https://github.com/ROCm/TheRock/issues/3336

On
https://github.com/ROCm/TheRock/actions/runs/23663263447/job/68945135064?pr=4209,
log upload failed since the configure credentials step did not run:

```
WARNING:_therock_utils.storage_backend:S3 upload attempt 1/3 failed for s3://therock-ci-artifacts/23663263447-windows/logs/math-libs/gfx110X-all/hipBLAS-common_install.log: Failed to upload B:\build\logs\hipBLAS-common_install.log to therock-ci-artifacts/23663263447-windows/logs/math-libs/gfx110X-all/hipBLAS-common_install.log: An error occurred (AccessDenied) when calling the PutObject operation: User: arn:aws:iam::692859939525:user/therock-external-upload is not authorized to perform: s3:PutObject on resource: "arn:aws:s3:::therock-ci-artifacts/23663263447-windows/logs/math-libs/gfx110X-all/hipBLAS-common_install.log" because no identity-based policy allows the s3:PutObject action. Retrying in 1.0s...

RuntimeError: Failed to upload 88/88 files. First failure: s3://therock-ci-artifacts/23663263447-windows/logs/math-libs/gfx110X-all/hipBLAS-common_install.log: S3 upload failed after 3 attempts: s3://therock-ci-artifacts/23663263447-windows/logs/math-libs/gfx110X-all/hipBLAS-common_install.log
```

This fixes that by copying the pattern from CI to multi-arch CI:
https://github.com/ROCm/TheRock/blob/4a115c720d51397c61a0efd7cc370fb78d862e80/.github/workflows/build_portable_linux_artifacts.yml#L170-L185

## Submission Checklist

- [x] Look over the contributing guidelines at
https://github.com/ROCm/ROCm/blob/develop/CONTRIBUTING.md#pull-requests.