[ci] Adding reproduction script (#4016)
Instead of a `print_test_reproduction_step` script, we will be creating
a reproduction script for both Linux and Windows

Linux test locally: 
```
nod@Shark52:~/geomin12/TheRock$ sudo  python3 build_tools/github_actions/reproduce_test_failure.py --run-id 22984573979 --repository ROCm/TheRock --amdgpu-family gfx94X-dcgpu --test-script "python build_tools/github_actions/test_executable_scripts/test_sanity.py"  --fetch-artifact-args="--base-only"
Unable to find image 'ghcr.io/rocm/no_rocm_image_ubuntu24_04:latest' locally
latest: Pulling from rocm/no_rocm_image_ubuntu24_04
01d7766a2e4a: Pull complete
6fa847d68076: Pull complete
61bfe1e33ebc: Pull complete
97c5f12fdab4: Pull complete
196c95c4716e: Pull complete
bbf6758019ac: Pull complete
54e461429258: Pull complete
b18d6aba31ef: Pull complete
4f4fb700ef54: Pull complete
Digest: sha256:93667a615fd7cfb24edcb89a4cb466d6c09131b59b3aeeebd63e7090bb75f1f5
Status: Downloaded newer image for ghcr.io/rocm/no_rocm_image_ubuntu24_04:latest
[1/7] Installing uv
downloading uv 0.10.11 x86_64-unknown-linux-gnu
no checksums to verify
installing to /home/tester/.local/bin
  uv
  uvx
everything's installed!

To add $HOME/.local/bin to your PATH, either restart your shell or run:

    source $HOME/.local/bin/env (sh, bash, zsh)
    source $HOME/.local/bin/env.fish (fish)
[2/7] Cloning TheRock
Cloning into 'TheRock'...
remote: Enumerating objects: 44427, done.
remote: Counting objects: 100% (2812/2812), done.
remote: Compressing objects: 100% (1149/1149), done.
remote: Total 44427 (delta 2465), reused 1671 (delta 1663), pack-reused 41615 (from 4)
Receiving objects: 100% (44427/44427), 19.40 MiB | 30.75 MiB/s, done.
Resolving deltas: 100% (30215/30215), done.
[3/7] Creating virtual environment
Using CPython 3.12.3 interpreter at: /usr/bin/python3
Creating virtual environment at: .venv
Activate with: source .venv/bin/activate
[4/7] Installing dependencies
Resolved 38 packages in 545ms
      Built perfetto==0.7.0
Prepared 38 packages in 314ms
Installed 38 packages in 46ms
 + attrs==25.4.0
...
 + urllib3==2.6.3
 + wcwidth==0.6.0
[5/7] Downloading artifacts
### Installing TheRock using artifacts ###
Creating output directory '/home/tester/TheRock/therock-build'
Created output directory '/home/tester/TheRock/therock-build'
Retrieving artifacts for run ID 22984573979

Calling fetch_artifacts_main with args:
  --run-id 22984573979 --artifact-group gfx94X-dcgpu --output-dir therock-build --flatten core-hipinfo_run core-runtime_run core-runtime_lib sysdeps_lib base_run base_lib amd-llvm_run amd-llvm_lib core-amdsmi_run core-amdsmi_lib core-hip_lib core-hip_dev core-kpack_lib core-ocl_lib core-ocl_dev rocprofiler-sdk_lib host-suite-sparse_lib

Retrieving bucket info...
  (implicit) github_repository: ROCm/TheRock
Warning: No GitHub auth available, requests may be rate limited
  workflow_run_id             : 22984573979
  head_github_repository      : ROCm/TheRock
  is_pr_from_fork             : False
Retrieved bucket info:
  external_repo:
  bucket       : therock-ci-artifacts
Retrieving artifacts from 's3://therock-ci-artifacts/22984573979-linux'
Matching artifact target families: ['generic', 'gfx94X-dcgpu']


Filtered artifacts to download:
  s3://therock-ci-artifacts/22984573979-linux/amd-llvm_lib_generic.tar.xz
...
++ Flattening 'amd-llvm_run_generic.tar.xz' to 'amd-llvm_run_generic'
++ Flattening 'amd-llvm_lib_generic.tar.xz' to 'amd-llvm_lib_generic'
Retrieved artifacts for run ID 22984573979
[6/7] Setting environment variables
[7/7] Running test
INFO:root:++ Exec [/home/tester/TheRock]$ /home/tester/TheRock/.venv/bin/python -m pytest tests/ --log-cli-level=info --timeout=300
=================================================================== test session starts ====================================================================
platform linux -- Python 3.12.3, pytest-9.0.0, pluggy-1.6.0
rootdir: /home/tester/TheRock
plugins: cov-6.0.0, timeout-2.4.0, check-2.5.3
timeout: 300.0s
timeout method: signal
timeout func_only: False
collected 8 items

tests/test_artifact_structure.py::TestArtifactStructure::test_no_cross_artifact_overlaps SKIPPED (THEROCK_ARTIFACTS_DIR not set)                     [ 12%]
tests/test_artifact_structure.py::TestArtifactStructure::test_no_within_artifact_component_overlaps SKIPPED (THEROCK_ARTIFACTS_DIR not set)          [ 25%]
tests/test_rocm_sanity.py::TestROCmSanity::test_rocm_output[rocminfo - GPU Device Type Search]
...
smitst '--gtest_filter=amdsmitstReadOnly.*:amdsmitstReadWrite.Fan...
==================================================== 5 failed, 1 passed, 2 skipped, 1 warning in 1.57s =====================================================
Traceback (most recent call last):
  File "/home/tester/TheRock/build_tools/github_actions/test_executable_scripts/test_sanity.py", line 44, in <module>
    subprocess.run(cmd, cwd=THEROCK_DIR, env=env, check=True)
  File "/usr/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/tester/TheRock/.venv/bin/python', '-m', 'pytest', 'tests/', '--log-cli-level=info', '--timeout=300']' returned non-zero exit status 1.
Test failed with exit code 1
tester@6f0ae85b24e4:~/TheRock$
tester@6f0ae85b24e4:~/TheRock$ ls
BUILD_TOPOLOGY.toml  FLAGS.cmake  SUPPORTED_GPUS.md  compiler     docs             media-libs             requirements.txt  third-party
CLAUDE.md            LICENSE      base               core         examples         ml-libs                rocm-libraries    version.json
CMakeLists.txt       README.md    build_tools        dctools      external-builds  patches                rocm-systems
CMakePresets.json    RELEASES.md  cmake              debug-tools  iree-libs        profiler               tests
CONTRIBUTING.md      ROADMAP.md   comm-libs          dockerfiles  math-libs        requirements-test.txt  therock-build
tester@6f0ae85b24e4:~/TheRock$ cd therock-build/bin/
tester@6f0ae85b24e4:~/TheRock/therock-build/bin$ ls
amd-smi   amdclang++   amdclang-cpp  amdlld  hipcc_check  offload-arch  rocm_agent_enumerator
amdclang  amdclang-cl  amdflang      hipcc   hipconfig    rocm-smi      rocminfo
tester@6f0ae85b24e4:~/TheRock/therock-build/bin$
```


Windows test:
```
shark-strixhalo-9@SHARK-STRIXHALO C:\Users\shark-strixhalo-9\geo-tes-3\TheRock> python build_tools/github_actions/reproduce_test_failure.py --run-id 22984573979 --repository ROCm/TheRock --amdgpu-family gfx110X-all --test-script "python build_tools/github_actions/test_executable_scripts/test_sanity.py"  --fetch-artifact-args="--base-only"
============================================================
WINDOWS REPRODUCTION (bare metal)
============================================================

Already installed:
  - chocolatey
  - git
  - python
  - cmake
  - ninja
  - ccache

This will install the following packages on your system:
  - uv

Continue? [y/N] y

[1/7] Installing uv
downloading uv 0.10.11 (x86_64-pc-windows-msvc)
installing to C:\Users\shark-strixhalo-9\.local\bin
  uv.exe
  uvx.exe
  uvw.exe
everything's installed!

To add C:\Users\shark-strixhalo-9\.local\bin to your PATH, either restart your shell or run:

    set Path=C:\Users\shark-strixhalo-9\.local\bin;%Path%   (cmd)
    $env:Path = "C:\Users\shark-strixhalo-9\.local\bin;$env:Path"   (powershell)
[2/7] Refreshing environment for uv
[3/7] Creating virtual environment
Using CPython 3.13.7 interpreter at: C:\Python313\python.exe
Creating virtual environment at: .venv
Activate with: .venv\Scripts\activate
[4/7] Installing Python dependencies
Resolved 37 packages in 1.74s
      Built perfetto==0.7.0
Prepared 37 packages in 2.50s
Installed 37 packages in 1.20s
 + attrs==25.4.0
...
 + wcwidth==0.6.0
[5/7] Downloading artifacts
### Installing TheRock using artifacts ###
Creating output directory 'C:\Users\shark-strixhalo-9\geo-tes-3\TheRock\therock-build'
Created output directory 'C:\Users\shark-strixhalo-9\geo-tes-3\TheRock\therock-build'
Retrieving artifacts for run ID 22984573979

Calling fetch_artifacts_main with args:
  --run-id 22984573979 --artifact-group gfx110X-all --output-dir therock-build --flatten core-hipinfo_run core-runtime_run core-runtime_lib sysdeps_lib base_run base_lib amd-llvm_run amd-llvm_lib core-amdsmi_run core-amdsmi_lib core-hip_lib core-hip_dev core-ocl_lib core-ocl_dev rocprofiler-sdk_lib host-suite-sparse_lib

Retrieving bucket info...
  (implicit) github_repository: ROCm/TheRock
Warning: No GitHub auth available, requests may be rate limited
  workflow_run_id             : 22984573979
  head_github_repository      : ROCm/TheRock
  is_pr_from_fork             : False
Retrieved bucket info:
  external_repo:
  bucket       : therock-ci-artifacts
Retrieving artifacts from 's3://therock-ci-artifacts/22984573979-windows'
Matching artifact target families: ['generic', 'gfx110X-all']

Filtered artifacts to download:
  s3://therock-ci-artifacts/22984573979-windows/amd-llvm_lib_generic.tar.xz
...
++ Flattening 'amd-llvm_run_generic.tar.xz' to 'amd-llvm_run_generic'
Retrieved artifacts for run ID 22984573979
[6/7] Setting environment variables
[7/7] Running test
INFO:root:++ Exec [C:\Users\shark-strixhalo-9\geo-tes-3\TheRock]$ C:\Users\shark-strixhalo-9\geo-tes-3\TheRock\.venv\Scripts\python.exe -m pytest tests/ --log-cli-level=info --timeout=300
=================================================================== test session starts ===================================================================
platform win32 -- Python 3.13.7, pytest-9.0.0, pluggy-1.6.0
rootdir: C:\Users\shark-strixhalo-9\geo-tes-3\TheRock
plugins: check-2.5.3, cov-6.0.0, timeout-2.4.0
timeout: 300.0s
timeout method: thread
timeout func_only: False
collected 8 items

tests/test_artifact_structure.py::TestArtifactStructure::test_no_cross_artifact_overlaps SKIPPED (THEROCK_ARTIFACTS_DIR not set)                     [ 12%]
tests/test_artifact_structure.py::TestArtifactStructure::test_no_within_artifact_component_overlaps SKIPPED (THEROCK_ARTIFACTS_DIR not set)          [ 25%]
tests/test_rocm_sanity.py::TestROCmSanity::test_rocm_output[rocminfo - GPU Device Type Search] SKIPPED (rocminfo is not supported on Windows)        [ 37%]
tests/test_rocm_sanity.py::TestROCmSanity::test_rocm_output[rocminfo - GFX Name Search] SKIPPED (rocminfo is not supported on Windows)               [ 50%]
tests/test_rocm_sanity.py::TestROCmSanity::test_rocm_output[rocminfo - AMD Vendor Name Search] SKIPPED (rocminfo is not supported on Windows)        [ 62%]
tests/test_rocm_sanity.py::TestROCmSanity::test_hip_printf
---------------------------------------------------------------------- live log call ----------------------------------------------------------------------
INFO     test_rocm_sanity:test_rocm_sanity.py:33 ++ Run [None]$ 'C:\Users\shark-strixhalo-9\geo-tes-3\TheRock\therock-build\lib\llvm\bin\offload-arch.exe'
INFO     test_rocm_sanity:test_rocm_sanity.py:33 ++ Run [C:\Users\shark-strixhalo-9\geo-tes-3\TheRock\therock-build\bin]$ 'C:\Users\shark-strixhalo-9\geo-tes-3\TheRock\therock-build\bin/hipcc' 'C:\Users\shark-strixhalo-9\geo-tes-3\TheRock\tests\hipcc_check.cpp' -Xlinker '-rpath=C:\Users\shark-strixhalo-9\geo-tes-3\TheRock\therock-build\bin/../lib/' --offload-arch=gfx1151 -o hipcc_check.exe
INFO     test_rocm_sanity:test_rocm_sanity.py:33 ++ Run [C:\Users\shark-strixhalo-9\geo-tes-3\TheRock\therock-build\bin]$ hipcc_check
PASSED                                                                                                                                               [ 75%]
tests/test_rocm_sanity.py::TestROCmSanity::test_rocm_agent_enumerator SKIPPED (rocm_agent_enumerator is not supported on Windows)                    [ 87%]
tests/test_rocm_sanity.py::TestROCmSanity::test_amdsmi_suite SKIPPED (amdsmitst is not supported on Windows)                                         [100%]

==================================================================== warnings summary =====================================================================
tests\extended_tests\utils\exceptions.py:39
  C:\Users\shark-strixhalo-9\geo-tes-3\TheRock\tests\extended_tests\utils\exceptions.py:39: PytestCollectionWarning: cannot collect test class 'TestExecutionError' because it has a __init__ constructor (from: tests/extended_tests/functional/scripts/test_miopendriver_conv.py)
    class TestExecutionError(FrameworkException):

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
========================================================= 1 passed, 7 skipped, 1 warning in 5.74s =========================================================

shark-strixhalo-9@SHARK-STRIXHALO C:\Users\shark-strixhalo-9\geo-tes-3\TheRock>
```

Intentional Linux fail to print steps:
https://github.com/ROCm/TheRock/actions/runs/23027595757/job/66879054713#step:13:31
Intentional Windows fail to print steps:
https://github.com/ROCm/TheRock/actions/runs/23027595757/job/66879120731#step:12:30

---------

Co-authored-by: Claude Opus 4.6 <noreply@anthropic.com>