[ci] Update workflow to use internal ubuntu container instead of public (#5795)
Replace ubuntu:24.04 with ghcr.io/rocm/no_rocm_image_ubuntu24_04:latest
in the multi-arch build native packages workflow and the container image
lookup used by the test native packages install workflow.

## Motivation

We're hitting Docker rate limits o.O [Link per-ISA device files into
rocm-sdk-devel by marbre · Pull Request #5778 ·
ROCm/TheRock](https://github.com/ROCm/TheRock/pull/5778)
```
Starting job container
/usr/bin/docker pull ubuntu:24.04
Error response from daemon: toomanyrequests: You have reached your unauthenticated pull rate limit. [Docker Hub usage and limits](https://www.docker.com/increase-rate-limit)
Warning: Docker pull failed with exit code 1, back off 7.153 seconds before retry.
/usr/bin/docker pull ubuntu:24.04
Error response from daemon: toomanyrequests: You have reached your unauthenticated pull rate limit. [Docker Hub usage and limits](https://www.docker.com/increase-rate-limit)
Warning: Docker pull failed with exit code 1, back off 9.266 seconds before retry.
/usr/bin/docker pull ubuntu:24.04
Error response from daemon: toomanyrequests: You have reached your unauthenticated pull rate limit. [Docker Hub usage and limits](https://www.docker.com/increase-rate-limit)
Error: Docker pull failed with exit code 1

```
## Test Plan

CI testing pass can be treated as pass