Add install retries to setup_venv.py to de-flake python test jobs (#5827)
## Motivation

Tentative fix for https://github.com/ROCm/TheRock/issues/5455. Our build
jobs produce and upload packages and then server-side code regenerates
index pages to include those packages. Queue time on the server-side
functions is set to 60 seconds to debounce similar requests. If a test
job is scheduled before the server-side code finishes running then tests
fail with errors like
```
++ Exec [B:\runner\_work\rockrel\rockrel]$ 'B:\runner\_work\rockrel\rockrel\.venv\Scripts\python.exe' -m pip install --index-url=https://rocm.nightlies.amd.com/whl-multi-arch/ 'torch[device-gfx1100,device-gfx1101,device-gfx1102,device-gfx1103]==2.9.1+rocm7.14.0a20260612'
Looking in indexes: https://rocm.nightlies.amd.com/whl-multi-arch/
ERROR: Could not find a version that satisfies the requirement torch==2.9.1+rocm7.14.0a20260612 (from versions: 2.9.1+rocm7.14.0a20260521, 2.9.1+rocm7.14.0a20260522, 2.9.1+rocm7.14.0a20260524, 2.9.1+rocm7.14.0a20260525, 2.9.1+rocm7.14.0a20260526, 2.9.1+rocm7.14.0a20260527, 2.9.1+rocm7.14.0a20260528, 2.9.1+rocm7.14.0a20260529, 2.9.1+rocm7.14.0a20260531, 2.9.1+rocm7.14.0a20260601, 2.9.1+rocm7.14.0a20260602, 2.9.1+rocm7.14.0a20260603, 2.9.1+rocm7.14.0a20260604, 2.9.1+rocm7.14.0a20260605, 2.9.1+rocm7.14.0a20260606, 2.9.1+rocm7.14.0a20260607, 2.9.1+rocm7.14.0a20260611, 2.10.0+rocm7.14.0a20260521, 2.10.0+rocm7.14.0a20260522, 2.10.0+rocm7.14.0a20260524, 2.10.0+rocm7.14.0a20260525, 2.10.0+rocm7.14.0a20260526, 2.10.0+rocm7.14.0a20260527, 2.10.0+rocm7.14.0a20260528, 2.10.0+rocm7.14.0a20260529, 2.10.0+rocm7.14.0a20260601, 2.10.0+rocm7.14.0a20260602, 2.10.0+rocm7.14.0a20260603, 2.10.0+rocm7.14.0a20260604, 2.10.0+rocm7.14.0a20260605, 2.10.0+rocm7.14.0a20260606, 2.10.0+rocm7.14.0a20260607, 2.10.0+rocm7.14.0a20260608, 2.10.0+rocm7.14.0a20260611, 2.11.0+rocm7.14.0a20260521, 2.11.0+rocm7.14.0a20260522, 2.11.0+rocm7.14.0a20260524, 2.11.0+rocm7.14.0a20260525, 2.11.0+rocm7.14.0a20260526, 2.11.0+rocm7.14.0a20260527, 2.11.0+rocm7.14.0a20260528, 2.11.0+rocm7.14.0a20260529, 2.11.0+rocm7.14.0a20260531, 2.11.0+rocm7.14.0a20260601, 2.11.0+rocm7.14.0a20260602, 2.11.0+rocm7.14.0a20260603, 2.11.0+rocm7.14.0a20260604, 2.11.0+rocm7.14.0a20260605, 2.11.0+rocm7.14.0a20260606, 2.11.0+rocm7.14.0a20260607, 2.11.0+rocm7.14.0a20260611, 2.12.0+rocm7.14.0a20260521, 2.12.0+rocm7.14.0a20260522, 2.12.0+rocm7.14.0a20260524, 2.12.0+rocm7.14.0a20260525, 2.12.0+rocm7.14.0a20260526, 2.12.0+rocm7.14.0a20260527, 2.12.0+rocm7.14.0a20260528, 2.12.0+rocm7.14.0a20260529, 2.12.0+rocm7.14.0a20260531, 2.12.0+rocm7.14.0a20260601, 2.12.0+rocm7.14.0a20260602, 2.12.0+rocm7.14.0a20260603, 2.12.0+rocm7.14.0a20260604, 2.12.0+rocm7.14.0a20260605, 2.12.0+rocm7.14.0a20260606, 2.12.0+rocm7.14.0a20260607, 2.12.0+rocm7.14.0a20260608, 2.12.0+rocm7.14.0a20260611, 2.13.0a0+rocm7.14.0a20260521, 2.13.0a0+rocm7.14.0a20260527)
ERROR: No matching distribution found for torch==2.9.1+rocm7.14.0a20260612
```

> [!NOTE]
> This mostly affects our automated CI/CD systems. Individual
users/developers who run install commands are not often running these
commands within 1-2 minutes of the build jobs completing.
Users/developers also typically don't pin an exact version like CI/CD
workflows do, so they just install slightly older packages in the common
case.

## Technical Details

This adds retry with timeout behavior _to each GPU test runner_ during
python package installs to account for the delay in server-side index
generation from running. I considered a few other options:

1. Add a fixed wait between 30 seconds and 2 minutes after the upload
jobs.
* This would save GPU runner time but would be unreliable if generation
is slower than usual. It could also waste CPU runner time if the
generation is faster than usual.
* This could also help with native Linux/Windows packages, tarballs, and
other workflows that involve asynchronous index generation and other
post-upload-processing steps.
* This could compose with the retries added here, providing two ways to
mitigate the race condition.
2. After uploading, query the remote server index pages and check for
the recently uploaded files
* I can't think of a robust (and _simple_) way to do this. For Python
packages we could use https://pip.pypa.io/en/latest/cli/pip_index/ but
we'd realistically have to check "is
torch-2.10.0+rocm7.14.0a20260522-cp311-cp311-linux_x86_64.whl there?",
"is torch-2.10.0+rocm7.14.0a20260522-cp310-cp310-linux_x86_64.whl
there?", etc. for all the packages that each job uploads. At that point
we might as well parse the HTML pages themselves... ick
3. Wait for some "index generation complete" signal from the server
* I think RPC calls would be the most robust solution here. Define some
API endpoint that build jobs can post to with "upload these packages:
<files>", then have the server mediate the upload and index generation
then send back a "upload complete" response. Right now we just push raw
files to S3 and let an AWS lambda function independently run whatever
code it wants, without keeping that connection or signalling back to the
uploading code that all operations are complete.

## Test Plan

Watch CI/CD workflow runs to see if the retry code is being used, is
sufficient, and works.

Tested the retry behavior locally:

```
λ python D:\projects\TheRock\build_tools/setup_venv.py test_pip.venv --packages rocm[libraries]==1.2.3 --index-url https://rocm.nightlies.amd.com/whl-multi-arch/ --install-retry-delay-seconds=2 --install-retry-seconds=20
Creating venv at 'test_pip.venv'
  Dir relative to CWD: 'test_pip.venv'
  Dir fully resolved : 'D:\scratch\therock\test_pip.venv'

  Found existing python executable at 'D:\scratch\therock\test_pip.venv\Scripts\python.exe', skipping creation
  Run again with --clean to clear the existing directory instead

++ Exec [D:\scratch\therock]$ 'test_pip.venv\Scripts\python.exe' -m pip install --upgrade pip
Requirement already satisfied: pip in .\test_pip.venv\Lib\site-packages (26.1.2)

++ Exec [D:\scratch\therock]$ 'test_pip.venv\Scripts\python.exe' -m pip install --index-url=https://rocm.nightlies.amd.com/whl-multi-arch/ 'rocm[libraries]==1.2.3'
Looking in indexes: https://rocm.nightlies.amd.com/whl-multi-arch/
ERROR: Could not find a version that satisfies the requirement rocm==1.2.3 (from versions: 7.13.0a20260425, 7.13.0a20260426, 7.13.0a20260427, 7.13.0a20260428, 7.13.0a20260430, 7.13.0a20260501, 7.13.0a20260502, 7.13.0a20260503, 7.13.0a20260504, 7.13.0a20260505, 7.13.0a20260506, 7.13.0a20260507, 7.13.0a20260508, 7.13.0a20260509, 7.13.0a20260510, 7.13.0a20260511, 7.13.0a20260512, 7.13.0a20260513, 7.13.0a20260514, 7.13.0a20260515, 7.14.0a20260518, 7.14.0a20260519, 7.14.0a20260520, 7.14.0a20260521, 7.14.0a20260522, 7.14.0a20260523, 7.14.0a20260524, 7.14.0a20260525, 7.14.0a20260526, 7.14.0a20260527, 7.14.0a20260528, 7.14.0a20260529, 7.14.0a20260531, 7.14.0a20260601, 7.14.0a20260602, 7.14.0a20260603, 7.14.0a20260604, 7.14.0a20260605, 7.14.0a20260606, 7.14.0a20260607, 7.14.0a20260608, 7.14.0a20260611, 7.14.0a20260612)
ERROR: No matching distribution found for rocm==1.2.3
Command failed (attempt 1, exit code 1); retrying in 2s...
++ Exec [D:\scratch\therock]$ 'test_pip.venv\Scripts\python.exe' -m pip install --index-url=https://rocm.nightlies.amd.com/whl-multi-arch/ 'rocm[libraries]==1.2.3'
Looking in indexes: https://rocm.nightlies.amd.com/whl-multi-arch/
ERROR: Could not find a version that satisfies the requirement rocm==1.2.3 (from versions: 7.13.0a20260425, 7.13.0a20260426, 7.13.0a20260427, 7.13.0a20260428, 7.13.0a20260430, 7.13.0a20260501, 7.13.0a20260502, 7.13.0a20260503, 7.13.0a20260504, 7.13.0a20260505, 7.13.0a20260506, 7.13.0a20260507, 7.13.0a20260508, 7.13.0a20260509, 7.13.0a20260510, 7.13.0a20260511, 7.13.0a20260512, 7.13.0a20260513, 7.13.0a20260514, 7.13.0a20260515, 7.14.0a20260518, 7.14.0a20260519, 7.14.0a20260520, 7.14.0a20260521, 7.14.0a20260522, 7.14.0a20260523, 7.14.0a20260524, 7.14.0a20260525, 7.14.0a20260526, 7.14.0a20260527, 7.14.0a20260528, 7.14.0a20260529, 7.14.0a20260531, 7.14.0a20260601, 7.14.0a20260602, 7.14.0a20260603, 7.14.0a20260604, 7.14.0a20260605, 7.14.0a20260606, 7.14.0a20260607, 7.14.0a20260608, 7.14.0a20260611, 7.14.0a20260612)
ERROR: No matching distribution found for rocm==1.2.3
Command failed (attempt 2, exit code 1); retrying in 2s...
```

## Submission Checklist

- [x] Look over the contributing guidelines at
https://github.com/ROCm/ROCm/blob/develop/CONTRIBUTING.md#pull-requests.