Revert "[ci] Improving multi arch CI for external repos " (#5698)
Reverts ROCm/TheRock#5450 to fix
https://github.com/ROCm/TheRock/issues/5654

This broke CI on PRs from forks, e.g.
https://github.com/ROCm/TheRock/actions/runs/26984086713?pr=5531:
```
Error: Could not assume role with user credentials: User: arn:aws:sts::324352301041:assumed-role/therock-runners-prod-runner-s3-external/aws-sdk-js-session-1780614257367 is not authorized to perform: sts:TagSession on resource: arn:aws:iam::692859939525:role/therock-ci-external
```